import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import axios from 'axios';


export default function Home() {

  const [creatorList, setCreatorList] = useState([]);

  useEffect(() => {
    axios.get('https://test-connect.api.clo-set.com/api/Social/354/Followers')
      .then((response) => {
        setCreatorList(response.data.users);
        // console.log("--------- creator(index.js) : ", creatorList)
      })
      .catch((error) => {
        console.error('Error fetching data:', error);
      });
  }, [creatorList]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Closet Connect Onboarding 2 by jhin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {creatorList.map((creator) => (
          <div className={styles.grid} key={creator.userId}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>{creator.nickName}</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
