import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react';
import axios from 'axios';

export default function Home() {
  const creatorsInputObj = {
    "keyword": "",
    "countries": [],
    "occupations": [
      2
    ],
    "pageNo": 1,
    "pageSize": 24,
    "defaultSortBy": 1,
    "sortby": 2
  };
  const [creatorList, setCreatorList] = useState([]);

  useEffect(() => {
    axios.post('https://test-connect.api.clo-set.com/api/creators', creatorsInputObj)
      .then((response) => {
        setCreatorList(response.data.creators);
        // console.log("creatorList(index.js)", creatorList)
      })
      .catch((error) => {
        console.error('Error fetching data:', error);
      });
  }, []); // creatorList를 의존성 배열에서 제거

  return (
    <div className={styles.container}>
      <Head>
        <title>Closet Connect Onboarding 2 by jhin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {creatorList.map((dataObj) => (
          <div className={styles.grid} key={dataObj.userId}>
            <div className={styles.card}>
              <h2>{dataObj.creator}</h2>
              <div className={styles.joblist}>
                {
                  dataObj.occupations.filter(occupation => occupation.name && occupation.name.trim() !== '').map((occupation, index) => (
                    <React.Fragment key={index}>
                      {index > 0 && ', '}
                      <span>{occupation.name}</span>
                    </React.Fragment>
                  ))
                }
              </div>
            </div>
          </div>
        ))}
      </main>
    </div>
  )
}
