import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { NATIONAL_CODE } from '../constants/nationalCode';
import { Button } from '@closet-design-system/core-connect';
import Carousel from "react-material-ui-carousel";

export default function Home({ creatorList, creatorIntro }) {

  console.log("creatorList : ", creatorList)

  const findCountryLabel = (countryCode) => {
    const country = NATIONAL_CODE.find(item => item.value === countryCode);
    return country ? country.label : '';
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Closet Connect Onboarding 2 by jhin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {creatorList.map((dataObj, index) => (
          <div className={styles.grid} key={dataObj.userId}>
            <div className={styles.card}>
              <h2>{dataObj.creator}</h2>
              <div className={styles.joblist}>
                {
                  dataObj.occupations.filter(occupation => occupation.name && occupation.name.trim() !== '').map((occupation, index) => (
                    <React.Fragment key={index}>
                      {index > 0 && ', '}
                      <span>{occupation.name}</span>
                    </React.Fragment>
                  ))
                }
              </div>
              <div>
                <p>{findCountryLabel(dataObj.country)}</p>
              </div>
              <div>
                {dataObj.photo && <img src={dataObj.photo} className={styles.creatorThumb} alt="Creator Thumbnail" />}
              </div>
              <div className={styles.introduction}>
                {dataObj.introduction !== "" && dataObj.introduction.ops.length > 0 && (
                  <p>{dataObj.introduction.ops[0].insert}</p>
                )}
              </div>
              <div className={styles.userInfo}>
                <Button
                  shape="fill"
                  size="sm"
                  variant="primary"
                  width="initial"
                >
                  FOLLOW
                </Button>
                <p>{dataObj.viewCount}</p>
                <p>{dataObj.likeCount}</p>
                <p>{dataObj.followerCount}</p>
              </div>
            </div>
            <div className={styles.slider}>
              <Carousel cycleNavigation={true} navButtonsAlwaysVisible={true}>
                {dataObj.items.map((content, index) => (
                  <div key={index}>
                    <img src={content.imagePath} />
                    {/*{content.desc.map((description) => (*/}
                    {/*  <li>{description}</li>*/}
                    {/*))}*/}
                  </div>
                ))}
              </Carousel>
            </div>
          </div>
        ))}
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const creatorsInputObj = {
    "keyword": "",
    "countries": [],
    "occupations": [
      2
    ],
    "pageNo": 1,
    "pageSize": 24,
    "defaultSortBy": 1,
    "sortby": 2
  };

  try {
    const response = await axios.post('https://test-connect.api.clo-set.com/api/creators', creatorsInputObj);
    const creatorList = response.data.creators;

    // Creator Introduction
    let creatorIntro = [];
    for(let i = 0; i < creatorList.length; i ++){
      if(creatorList[i].introduction !== "" && creatorList[i].introduction.ops !== [] && creatorList[i].introduction.ops[0]){
        creatorIntro.push(creatorList[i].introduction.ops[0].insert)
      } else {
        creatorIntro.push("")
      }
    }

    return {
      props: {
        creatorList: creatorList,
        creatorIntro: creatorIntro
      }
    };
  } catch (error) {
    console.error('Error fetching data:', error);
    return {
      props: {
        creatorList: []
      }
    };
  }
}


